### ISSUE TITLE
Specifying "Worker group"

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#14]
I understood your explanation on the difference between "Worker group" and "Groups."

Just to share my experience, when I was trying to manually add a contact to the contact list, the candidate names for Groups would populate so that I was just able to click on a name that was already created or I could create a new one. 

For the Worker group on the other hand, there was no candidate names that pop up, so I had to make sure that I type in the one of the Groups names correctly, for example, "village 2 - workers". Is this how I would do it? 

Of course, this assignment of a specific worker group to be sent the broadcast messages will be easy enough when I actually create a list from STATA, a data processing program I use, but just wanted to make sure if this is how I would do it now.

**Comment by craigloftus** [comment]
Yeah, that is how you should be doing it now.
