### ISSUE TITLE
farm location, confirmation of the recruit request, and job announcement

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#15]
Replying to your issue #12 made me realize one other thing, which is to confirm the farmer's farm location. We know farmer's residential village at the time of registration and it will be imported into contact list. For now I am restricting this service for the farms in the farmer's residential village only (but not for the farms outside the farmer's residential village). In future, we could add in a question "You have farms in two villages. Reply 1 to hire in Mikochecni and 2 to hire in Kiboroloni." 

But for now I don't have a plan for this. 

In any case, the modification will be:

```
So that is [x] workers [y] days for [harvesting] for [2.5] acres in [mikocheni] village, and you will pay [per acre]. Reply 1 to confirm and 0 to start over.
> 1
We'll get back to you with offers from people in your area.

So that is [x] workers [y] days for [harvesting] for [2.5] acres in [mikocheni] village, and you will pay [per acre]. Reply 1 to confirm and 0 to start over.
> 0
Great. How many workers are you looking for?
```

From the worker's perspective, it is important to let them know the location of farm village, because for a different group of villages, workers living in an adjacent village could also receive the announcements.

If the employer is paying [per day]:
```
[DJ] is hiring [x] workers for [x] days for [harvesting] for [2.5] acres in [mikocheni] village. To make an offer, reply: #91023
> #91023
Ok. How much do you want to get paid [per day]? 
```

If the employer is paying [per acre]:
```
[DJ] is hiring [x] workers for [x] days for [harvesting] for [2.5] acres in [mikocheni] village. To make an offer, reply: #91023
> #91023
Ok. How much do you want to get paid [per acre]? The payment will be split with other workers the employer will hire.
```

**Comment by craigloftus** [comment]
@dajeong265 Just to clarify, the only change you're asking me to make is to add the village to the message content?

**Comment by dajeong265** [comment]
No. There are more. 

Can you add all changes I mentioned exactly as in the examples above?
- adding the farm acreage
- adding the village location
- confirming the request by 0, 1 reply (which we didn't have previously)
- message wordings

Does that make sense?

**Comment by craigloftus** [comment]
Yes that is fine. I was mostly just clarifying that you weren't asking for this bit:

```
You have farms in two villages. Reply 1 to hire in Mikochecni and 2 to hire in Kiboroloni.
```

**Comment by dajeong265** [comment]
Yeah, that's again may be a future issue if "time permitting." Don't worry about it now.
