### ISSUE TITLE
Hotline number

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#16]
I think we have to add a message with a hotline number people can call and ask for help. I am not sure exactly at which step we want to mention this, but here is my try and let me know what you think.

For workers, it could be when they first get a job announcement. For example, 
```
[DJ] is hiring [x] workers for [x] days for [harvesting] for [2.5] acres in [mikocheni] village. To make an offer, reply: #91023. Call [0766232518] for help. 
```

 For employers, it could be 
```
So that is [x] workers [y] days for [harvesting] for [2.5] acres in [mikocheni] village, and you will pay [per acre]. Reply 1 to confirm and 0 to start over. Call [0766232518] for help. 
```

If this is too long, we can make it short. This at least fits under 160 bytes.
```
[x] workers [y] days for [harvesting] for [2.5] acres in [mikocheni], and pay [per acre]. Reply 1 if correct and 0 to start over. Call [0766232518] for help.
```

**Comment by craigloftus** [comment]
This is just a case of changing the content of whichever messages you want to advertise a hotline in? I'd suggest you just add this when finalising the wording of the messages.
