### ISSUE TITLE
add a question to the employer "when does the job start"?

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#21]
I’ve received feedback from people here that it’d be good to add to the employer, 

> “when does the job start? Reply 0 for today, 1 for tomorrow, 2 for 2 days from today, 3 for 3 days from today”, 

and then also include this in the job announcement to workers.

**Comment by craigloftus** [comment]
The messages and number of interactions are getting out of control. Today I've added 

* pay by acre/day
* location
* number of acres
* confirm/cancel

To get even that to fit in the farmer summary I've add to go with a very compact representation:

```
So 3 workers, 2 days, 2 acres, paying in days. For harvesting in Kidlington. Reply 1 to confirm and 0 to cancel.
```

Obviously when the work will start is an important piece of information, but I think you need to review all the information you're asking for and what is being included in the messages to users. Including names of people and villages is particularly problematic from the point of view of ensuring consistent message length.

Please try out the service again and give me a final list of inputs and english messages you want to include for the trial, with an eye to message length?

**Comment by dajeong265** [comment]
Yeah, I am aware of that problem. Unfortunately it's an unnecessary trade off, and yes, as you said, it has to be eventually determined by the "average" user, because preferences differ across users.

For farmers' names and village names, they can be controlled. I know the names of all villages in the region, and the maximum length of villages is 18 bytes. For the first name, the maximum length is 12 bytes. There are some 2-word or 3-word names in my data, and I think it's a mistake of data entry, but in any case I can just collect the first word before I upload the farmer list to the Telerivet.

So, how about the following, which is 150 bytes? 
> 3 workers, 2 days, 2 acres, paying in days, starting 2 days from today for land preparation in 123456789012345678. Reply 1 to confirm and 0 to cancel.

For the job announcement to the workers, how about the following? This  is now 149 bytes with a hypothetical maximum length of farmer name and village name:
> 123456789012 is hiring 2 workers for 2 days of weeding on 0.5 acres, starting [2 days from today] in 123456789012345678. To apply, reply: Job 751223
