### ISSUE TITLE
How to best phrase instructions [To apply: Job 432912]

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#23]
I was doing some testing with local people here in Swahili, and there was one of our messages that said  >To make an offer, reply: Job 432912.

Some people understood it as replying "432912", while some people understood it as replying "Job".

We're going train farmers about this, but just making a note here to keep this in mind in the background.

**Comment by dajeong265** [comment]
That sounds great to me. If it's easy enough, please implement it. 

Otherwise, I'll be getting feedback from larger number of farmers in coming days.

**Comment by craigloftus** [comment]
How about we leave it, and in your paper testing you give the two options and take a vote? It is easy enough to change it, but I'd rather just change it once.

**Comment by dajeong265** [comment]
Make sense.
