### ISSUE TITLE
self-registration into services

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#24]
I’ve been trying to add more employers and employees to the contact list, but it seems a little too tedious to do it manually. Last time I told you that I might not want to have them to do self-registration because farmers could make spelling errors in the village names and we cannot then identify whether they belong to the same village or not. But on a second thought, it’d be useful if this can be done automatically "with some checks" on our side. For example, they could self-register themselves for names, phone numbers, whether they want to be an employer or an worker, but we could restrict the service until it’s verified/activated by us. I think the verification on our side anyway because we have to assign them specific service codes, especially when there are multiple versions of flows. 

Overall, self-registration seems doable, if we have them to self-register the basic information, and then during the process of verification on our end, we could add service codes ourselves, etc.

The basic information will be:
1. What is your first name?
2. What is your last name?
3. In which ward do you live?
4. In which village do you live?
5. Are you registering for this service as an employer or a worker? Reply 1 to register as an employer and 2 to register as a worker. You cannot register for both. 

Once these info are in our system, our staff will go through the names of village and ward to harmonize them.

**Comment by craigloftus** [comment]
I've labelled this `time permitting` as it isn't strictly in the spec, but it seems like it would be quite simple and I think there should time for it.

**Comment by craigloftus** [comment]
The only problem I can see is that if the village name is entered incorrectly then we won't be able to associate them with the other employers/workers in their village.

I could 'bodge' this slightly, such that it tries to associate them, if it fails then it sends you an sms telling you to do it manually?

> but not sure how to modify this when we have two different versions of codes

This would depend on how you're planning to implement and 'assign' different services. If it were based on village then we could create a custom data table, with a row for each village and columns for each service with the service id to copy into the contact (with a default set of services if the village isn't found in the data table)

**Comment by craigloftus** [comment]
> On the village name harmonization:
So, would you need a list of correctly spelled village names separately? Or, does it compare with the village names of other people already in the Contacts page? Also, what algorithm are you planning to use to associate misspelled villages with a correct village name, like Bigram or Levenshtein distance?

It would use the worker groups. So these would need to be defined in advance.

Whilst fuzzy matching sounds straightforward and appealing, it is not always a good choice, particularly for place names (I live in a village called Kidlington, 8 miles away is a village called Kiddington); unless place names in the experimental area are always significantly different?

> The service codes also differ by status (i.e. Employer variable), so you're saying for each village 
> name and status, we should have a pre-made table with services codes to refer to, which basically 
> can handle different versions of service codes? Could you elaborate a bit if I am mistaken?

It would still just be for each village in that case because the employer and worker use different services, you're not choosing different version of the same service based on whether they are a worker or not?

**Comment by dajeong265** [comment]
1. I agree on the limitation of fuzzy matching. I just checked the 100 village names that are planning to be included in my study and the village names look somewhat different. But I agree that fuzzy matching can't work 100% time. I can imagine having a staff member sitting in the office and fix the village names manually as the self-registration comes in (and as you suggested, the system can flag when it fails to match). Let me know if there is a better alternative.

Also if somebody tries to register a village name that is already not in the system or the list, then we should send the fallback message?


2. I see your point on the village names. Yes, you're right. Within village, the version will be fixed for employers and workers. Different versions are applied at the village level. Could you develop this in a flexible way so that I can apply/modify different versions myself later? 


Do you think this is enough for you to get started? Let me know if there are things or lists you need from me to get it started. I can create a csv file/template with village names/services if needed. I am just not sure of the exact format you want.

**Comment by dajeong265** [comment]
This is just a quick sketch of what it would look like. Feel free to modify them.

receive a msg "registration"
-> Check if this phone number already exists in the system with village names. If so, send "You're already registered as a worker/employer in the system. Contact XXXX for any other questions."
-> If it is a new phone number, then do the following. 

1. Thank you for your interest for our labor app service. We will ask you a few questions before you register into the system. what is your first name?
2. what is your last name?
3. what is your village name?
4. what is your gender? Reply 1 for Male and 2 for Female.
5. what is your age?
6. Reply 1 to register as a worker and 2 to register as an employer. You cannot register for both with a same phone number.
7a. (If the answer for Q6 is 1) Thank you. You're successfully registered. You will receive a message when somebody in your village is looking for workers. 
7b. (If the answer for Q6 is 1) Thank you. You're successfully registered. To start hiring, reply: Wafanyakazi.

**Comment by craigloftus** [comment]
Yes, that is enough to go on. I should be able to make a start tomorrow.
