### ISSUE TITLE
Random sample farmer surveys

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#25]
I think we've been mostly talking about post-hiring surveys so far (e.g. employers' experiences with the workers they hired). 

But just to remind ourselves, there is also another survey, "random sample farmer surveys", which is much easier to implement I believe. So basically farmers with some indicator would be sent a series of questions (with high frequency, e.g., weekly) to measure their labor time allocation between farm, casual work, business, etc. I believe I put in some 12 or so questions into the specification document that I shared earlier with you and Samir.

**Comment by craigloftus** [comment]
So the specification listed 6 questions:

1. How many hours did you work on your all plots for the past 7 days?
2. How many hours did your spouse work on your all plots for the past 7 days?
3. How many hours did other household members work on your all plots for the past 7 days?
4. How many hours did "paid" casual workers work on your all plots for the past 7 days?
5. How many hours did your friends and neighbors work on your all plots "for free" for the past 7 days?
6. How many hours did you work on someone else's plots for free for the past 7 days?

The specification doesn't indicate how you would like these messages to be triggered? I think the best way would be to use a manually created scheduled broadcast (to a group containing the people you have randomly selected) that reads something like:

```
Hi. This is IPA with a short weekly survey to ask about your labor activities. To start, reply: Survey 123456

>Survey 123456

How many hours did you work on your all plots for the past 7 days?
```

Is that okay, and do you want to change any of the questions above before I start on it?

**Comment by dajeong265** [comment]
Triggering sounds good. Please use the survey questions here in the google sheet. 
https://docs.google.com/spreadsheets/d/1SF909TZAY-3pNtjTLiPzbov-UsPsfGBxH9R-7MTRPYs/edit#gid=1620575683

**Comment by craigloftus** [comment]
I've implemented the english and Swahili variants of this, though the Swahili variant needs some messages (failures and end message) translating.

I didn't need a code in the end, so it can be triggered by just sending "Random" to the number... obviously not a good keyword, I'd suggest using something like "feedback" for the post-hiring surveys and then using "survey" for the random surveys?
