### ISSUE TITLE
Adding a worker rating back into the farmer recruit

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#27]
Suppose we collected data on farmers' satisfaction on workers they hired.

What is the best way to loop this information back into the farmers' "recruit"?

I can imagine compiling the Contacts data set with this additional variable, and then call that variable in the "recruit" services. What do you think?

**Comment by craigloftus** [comment]
Wouldn't it make more sense to use that information when presenting offers? Something like "Bob offered TSh 2000 per day; he has a rating of 4 from 3 jobs."?

**Comment by dajeong265** [comment]
Yeah, maybe I didn't make it clear, but that's what I was trying to say.

This is something that I want to see their reactions, so one version of the flow will have this, while the other version wouldn't.

This was also in the proposal: 

> Farmers receive basic information such as worker name, worker’s preferred wage, years of experience, and the worker rating.

**Comment by craigloftus** [comment]
This is implemented now. Swahili view service needs its message logic updating to use the new variables.
