### ISSUE TITLE
start/stop keywords

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#29]
I think the logic has to change to understand the keyword for "start" versus "stop". 

Right now, it looks like it's based on the order, regardless of the keyword. For example, even if I send `start` for the first time, it'll say 

> Okay. You won't receive messages any more. If you want to start receiving messages, reply START at any time

But I want the Telerivet to complain when receiving `start` if the service is active, and vice versa.

**Comment by craigloftus** [comment]
I've split this service into two, so it no longer toggles irrespective of the keyword used.

**Comment by dajeong265** [comment]
Verified.
