### ISSUE TITLE
Feedback 1 and Feedback 1_Swahili

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#30]
I renamed the Survey 1 and Survey 1_Swahili to Feedback 1 and Feedback 1_Swahili.

I also updated both English and Swahili services in terms of the questions we ask as per farmers' feedback. 

Instead of asking "were there workers hired outside the messaging app", I just ask "What was the total number of casual workers worked on your farm for a job posted on [[date]]?" and then I will infer that there were workers hired outside the system if this number is different from the number of workers they hired through the app (which we observe). 

Another feedback was farmers were confused as to whether we were asking for a specific job post or in general. Hence I added "for a job posted on [[date]]" for all questions as I updated in the services. For example, 

> How much did you end up paying your workers per [[state.vars.payment]] for a job posted on [[date]]?
> Sorry I didn't get that. Please reply with the number of shillings you paid per [[state.vars.payment]] for a job posted on [[date]].

But I wasn't sure what the variable name for [[date]] is in the Telerivet. Telerivet did not allow me to use `[[date]]`, so I temporarily updated them using `[[$date]]`. Was there a variable name that stores this information? If so, could you suggest how to fix this?

**Comment by craigloftus** [comment]
I've sorted the date.

I've also renamed the `others` column to `total` to better reflect how you're using that question now.

**Comment by dajeong265** [comment]
Thanks for this. I'll test this once the Offer 1_Swahili is sorted out as I mentioned in the issue #32
