### ISSUE TITLE
Error in Offer 1_Swahili

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#32]
I was just trying to create a job request to test your new recent changes, but I faced an error for the service <offer 1_swahili>. 

I made a job announcement through 0766252318 as an employer and then applied for the job through 0754096298 as a worker. Everything worked well so far. But then when the Telerivet was trying to process the Offer 1_Swahili, I received this error in my email inbox. 

> Offer 1_swahili was unable to automatically process an incoming SMS from +255754096298: illegal character (action_2.js#21)

The offer message is supposed to be this
>You've had an offer of TSh [[$offer]] per [[$payment]] from someone in your area. To accept and get their details reply with: Offer [[$offer_code]]

But in the actual message received by 0766252318, all the variables were empty. Could you look into this?

**Comment by dajeong265** [comment]
I think it has to do with your most recent commits for offer/action_1.js and offer/action_2js. 
https://github.com/regulusweb/ucsc-tz-labor/commit/ac58b592131743cbb65874a25c070bd54570e0a7

**Comment by craigloftus** [comment]
Yeah, it was a problem with a change I made earlier today. It is fixed now.
