### ISSUE TITLE
View 1_Swahili not working

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#34]
I think for a similar reason as in offer 1_swahili, now View 1_swahili is not working. 

> View 1_swahili was unable to automatically process an incoming SMS from +255766232518: illegal character (action_1.js#65)

I don't know if they are related, but incidentally, when I tried to view in the employer's phone by typing "_Huduma 706997_", I just received "_Okay. You'll start receiving messages again. If you want to stop messages, reply STOP at any time_" in the worker's phone. 

Ok. And then I received your new service message "_You applied to a job posted by Dahyeon Jeong on Jul 9th. To tell us how it went, reply: Review7086997_"

When you experiment with the new services, just be careful not to add service codes to real farmers. We have added about 40 real farmers to the contacts page. Feel free to experiment with Dahyeon Jeong (employer) and DJ Tablet (worker). Those two numbers are mine.

**Comment by craigloftus** [comment]
I've fixed this issue. The odd message will be associated with this bug.
