### ISSUE TITLE
waiting time of 10 minutes

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#36]
I see in the most logic we set the waiting time to be 10 minutes. From my understanding, the active logic will break if Telerivet does not receive anything within 10 minutes?

1. My observation from testing is that, for MREJESHO (FEEDBACK), the logic works even if the reply was after 18 minutes. I've got a correct reply "Would you recommend [[$name]] to someone else? Reply 0 if you didn't hire them, and 1 to 5, for unlikely to very likely." But it didn’t work for HAKIKI (REVIEW) when replied after 14 minutes. 

All of my testings are based on Dahyeon Jeong (0766232518) and DJ Tablet (0754096298), so you can check the message interactions in Telerivet of those. 

2. Another thing is that it's hard to imagine for farmers to react within 10 minutes for the survey reminders (either FEEDBACK or REVIEW or RANDOM), because I imagine they don't check their phones that frequently. What's the reason behind that we cap the waiting time? Is it because if a particular service is open/active, then it conflicts with other possible services?

**Comment by craigloftus** [comment]
I tried to reproduce this a couple of times and can't. It seems to be working as expected for me on the simulator. If you're able to reproduce it again, then please point to specific messages in the log (there are rather a lot of messages against those 2 accounts).

**Comment by dajeong265** [comment]
I don't see this behavior any more. I think it might have been interacting with the poor mobile network at the time of testing.
