### ISSUE TITLE
FEEDBACK reminder coming instantly

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#38]
My understanding was that we would configure the FEEDBACK survey (for employers) timing on this file, `scripts/services/view/action_1.js`, and I set it to be 300 seconds. 

But I am getting the FEEDBACK survey instantly. 

See my phone number 0766232518 (Dahyeon Jeong) with the time stamp at July 12th, 10:37am (EAT). You can see that the following message is sent instantly at 10:37am, as soon as I "view" the worker's info. 
> Ulihitaji wafanyakazi [[num_workers]] kwa kazi uliyoitangaza tarehe [[date]]. Tungependa kuuliza kuhusu utendaji wao. Kushiriki jibu: MREJESHO [[survey_code]]

Please refer to the translation sheet if Swahili is confusing. 
https://docs.google.com/spreadsheets/d/1SF909TZAY-3pNtjTLiPzbov-UsPsfGBxH9R-7MTRPYs/edit#gid=0

**Comment by craigloftus** [comment]
This it is because the logic we're using there... you had asked that the survey be sent x days after the job was posted, so we take the time the job was originally posted and add an offset:

```
start_time: parseInt(survey.vars.posted)+300
```

When the time is reduced to a small number, by the time you get to using the `view` service the offset time has already past.

**Comment by dajeong265** [comment]
I had thought `survey.vars.posted` is the time when I complete my job post, not when I initiated? In other words, I had thought the time I receive this message is `survey.vars.posted`:

> Okay. We'll forward offers to you soon. When you've filled the position reply: Close [[state.vars.recruit_code]].

**Comment by craigloftus** [comment]
It is. The job post was completed at 10:29, an offer was then received at 10:36, you view it at 10:37, and because the scheduled message time (10:34; 29 + 5) had already occurred the survey message was sent immediately.

**Comment by dajeong265** [comment]
You're right. My bad. Thanks for clarifying.
