### ISSUE TITLE
Data tables

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#42]
All contacts, except for the two of your contacts, are currently using services in Swahili. But why is the data table with no Swahili subscript still being updated?
https://telerivet.com/p/2037d5f9/data?sort=-timeUpdated

For example, both offer (recruit) and Offer 1_swahili (recruit 1_swahili) have been updated. How are the data tables currently linked to the service codes?

**Comment by craigloftus** [comment]
It is a little confusing, but essentially, the telerivet services record all responses into data tables by default, but we also record more structured data into tables manually. So in the list of tables you're seeing both our maintained tables and the raw response tables.

If you edit a service and look at the advanced settings at the bottom there is an input where you can change the name of the data table it uses for these raw responses. I'd suggest change those to make it easier to distinguish them.

I would also suggest flushing all the data and contacts after you've finished your trial period; if that is possible?

**Comment by dajeong265** [comment]
So, I should make sure not to use the same name for the "raw response tables" and our "maintained tables"? 

I am now changing the table names to be [services name_raw].

**Comment by dajeong265** [comment]
Ok. 
- I cleaned all data in the data tables
- changed the table names
- deactivated English services.

For all the data tables, could you make sure to collect Contact ID / Phone number so that individuals can be potentially used to link across the tables? And of course offer_id and recruit_id are crucial, too. 

I'll generate some data into data tables and will actually try to merge them across to see where I have troubles. I'll be able to do this tonight.
