### ISSUE TITLE
Add a condition to process exception

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#45]
Could we add an exception rule to deal with this kind of error? See Sara's message at 5:49pm EAT in the screenshot.

![image](https://user-images.githubusercontent.com/24502003/42765611-152ca12e-8921-11e8-94ee-98d3a87bdb02.png)

**Comment by craigloftus** [comment]
From what I can tell her response was stored correctly and the reminder was cancelled. It may have occurred if you cleared out the scheduled messages manually?
