### ISSUE TITLE
Data Table misrecording in <Feedback 1_swahili_raw>

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#46]
I noticed that the data table in <Feedback 1_swahili_raw> is not properly recording all the responses. 

See this thread for Joseph Elias at 5:47pm EAT.
https://telerivet.com/p/2037d5f9/contact/CT106638114c9e967d

He rates two workers (DJ TIGO and DJ Tablet).

There are two issues:
- the table must record 2 separate recordings (1 for DJ TIGO and 1 for DJ Tablet). 
- the table must record who they are (contact ID for 1st rating and contact ID for 2nd rating). 

This table is the raw table, so you might be recording these already somewhere because we loop the rating information back into the workers' profile in the recruitment announcement.

**Comment by craigloftus** [comment]
This is being recorded in `survey_request`: https://telerivet.com/p/2037d5f9/data/survey_5Frequest

**Comment by dajeong265** [comment]
I see. They are recorded as separate rows (as opposed to separate columns). Didn't realize that. Thanks.
