### ISSUE TITLE
Self-registration suggested changes

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#49]
There are a few changes I made. 
1. I switched the order of worker and employer. 
- Previously, it was "reply 1 to register as a worker and 2 to register as an employer." 
- Now 1 is for employer and 2 is for worker. 

2. I wanted to use Employer variable in the contacts page to be automatically inputted. 
- Previously it was "set state.vars.type = 'worker'". 
- Now I changed it to be "contact.vars.employer = 1" or "contact.vars.employer = 0" because it is Yes/No variable and when I exported the data, it was coded as 1/0 binary. 
- I updated the [action_1.js](https://github.com/regulusweb/ucsc-tz-labor/blob/master/scripts/services/register/action_1.js) accordingly from `state.vars.type == 'Worker'` to `contact.vars.employer = 0`, and the same for employer.

3. I wanted to use the existing variable for gender, which is contact.vars.female. The register service code has been updated accordingly. 

4. Previously the feedback_service and view_service was not being updated when a person register as an employer. I added view_service into [action_1.js](https://github.com/regulusweb/ucsc-tz-labor/blob/master/scripts/services/register/action_1.js). I wanted to rename the `survey_service` to `feedback_service` in [router.js](https://github.com/regulusweb/ucsc-tz-labor/blob/56bfa5b2b858d6142edb55b17bc325451d6bc9e0/scripts/services/router.js), but it didn't work in my testing. So I renamed the `feedback_service` to `survey_service` instead in [action_1.js](https://github.com/regulusweb/ucsc-tz-labor/blob/master/scripts/services/register/action_1.js). Is there a way to fix this to be feedback_service across the board? How is this currently mapped into Telerivet? One related question is that what does this mean [here](https://telerivet.com/a/ACf387241d9c4e04ed/api) "Cloud Script API used by Recruit 1, Router, Offer 1, View 1, Close 1, Recruit 1_swahili, Feedback 1, Close 1_swahili, Offer 1_swahili, View 1_swahili?" Why is <Feedback 1_swahili> not here, and why are some of the old service names still there? 

One thing that is not working is the last step in the service code. Even if I use the village name that is already in the contacts page, Telerivet sends a SMS to +255766232518 to notify me. I had thought it would only send it when the village name is new.

**Comment by craigloftus** [comment]
>  I wanted to rename the survey_service to feedback_service in router.js, but it didn't work in my testing. So I renamed the feedback_service to survey_service instead in action_1.js. Is there a way to fix this to be feedback_service across the board? How is this currently mapped into Telerivet?

The keys in `router.js`, like `survey_service`, `view_service` correspond to the variables on the contacts, e.g., `contact.var.survey_service`. It looks like you were nearly there, but when editing the 'columns' in the contact directory you need to make sure to edit the `variable name` (this is what is used throughout the code) rather than just the `field name` (which is just for display):

https://telerivet.com/p/2037d5f9/contact_vars/v/survey_service/edit

> Cloud Script API used by Recruit 1, Router, Offer 1, View 1, Close 1, Recruit 1_swahili, Feedback 1, Close 1_swahili, Offer 1_swahili, View 1_swahili?" Why is <Feedback 1_swahili> not here, and why are some of the old service names still there?

This is referring just to services that use custom JS blocks in their definition; I guess it also lists inactive services as they can still be run in the simulator.

> One thing that is not working is the last step in the service code. Even if I use the village name that is already in the contacts page, Telerivet sends a SMS to +255766232518 to notify me. I had thought it would only send it when the village name is new.

This was working, in the sense it would only send a message for the first time someone used the register service for a specific group, which isn't quite what we want. I've modified it to also ignore non-empty groups, so it should behave as expected now.

**Comment by dajeong265** [comment]
Thank you for the quick reply. I can't still seem to get it to work. Anything I am missing?
- I updated router.js and action_1.js, and synced
- I updated the variable name to be contact.vars.feedback_service
<img width="599" alt="screen shot 2018-07-26 at 11 45 14 pm" src="https://user-images.githubusercontent.com/24502003/43287756-9a911ef2-912e-11e8-8033-eeb56bc80899.png">

**Comment by craigloftus** [comment]
It is probably because the user you're testing with does not have their `contact.vars.feedback_service` set?

**Comment by dajeong265** [comment]
How can a user who's registering for the first time have it set?

**Comment by dajeong265** [comment]
Thank you! I fixed and now it's working! Also I know it's not a crucial thing but do you have an answer to the following question, just out of my curiosity and to better understand your codes?

> Why isn't <Feedback 1_swahili> in there because it also runs JS blocks? That's the only thing I can think of in terms of why the feedback_service is not being updated.

>> This is referring just to services that use custom JS blocks in their definition; I guess it also lists inactive services as they can still be run in the simulator.


I'll also let you after I test assigning different versions by the village names in the `village services` data table.

**Comment by dajeong265** [comment]
I have a really quick question to ask. I added a message to confirm their registration details like we did for the recruitment details. And when farmers say they want to cancel and start over, I want to remove the contact so that they can start over, but not sure how to remove. In the action, there is only "remove contacts from a group ____ ", but not entirely from the contact page. 

Could you have a look at the last step in the services "Hakuna tatizo. Kujisajili, jibu: SAJILI" (No problem. To register, reply: SAJILI) and let me know if you have an idea?

**Comment by craigloftus** [comment]
You can only do that with custom JS: `contact.delete()`.

I can add that in if you like, once you've finished testing the assigning different service versions, along with any other changes you want made to the service before signing off.

**Comment by dajeong265** [comment]
Would it be as simple as adding an action "run javascript code", and then in the box, add
`contact.delete();`

or would it be something that has to be updated in the github?

I've finished testing the assigning different service versions, but you never know when I am done with changes. So I am just trying to make it work by myself.

**Comment by dajeong265** [comment]
I think I made it work!
