### ISSUE TITLE
contact field being automatically generated

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#50]
A field `survey_service` is automatically being created even after I delete it from the contacts page.

Additionally, a field name `worker group` is not being modified even if I rename it to display a different name. 

Could you point me to a source code where these behaviors can be corrected?

**Comment by craigloftus** [comment]
Can you point to a contact this has happened to and detail the steps to reproduce?

There are no references to `survey_service` in the code anymore.

**Comment by dajeong265** [comment]
Ok. I haven't been successful for replicating. For now, forget about the `survey_service`, but I just changed the `worker group` display to be `worker from`. And I will let you know when it is changed back to `worker group`.

**Comment by dajeong265** [comment]
Yes, I know exactly how this is working, but I don't know, for some reason, this variable name hasn't been so intuitive just for me.

I think of each row from an employer's perspective because this variable is only relevant for employers. Then when I look at it from an employer's angle, I think of this as "my potential **workers** are coming **from** [xxxxx] villages", hence "worker from." Is it still strange after my explanation?
