### ISSUE TITLE
FUNGA (CLOSE) action reliability

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#51]
FUNGA isn't working as expected in this particular case. I checked that FUNGA 699951 was correctly received by the router phone immediately on time.

You can see in the attached message it was `Funga 699951`. And then I tried again with `FUNGA 699951` and it worked and I got a success message. It's strange, because it shouldn't behave this way.
<img width="840" alt="screen shot 2018-07-28 at 12 34 37 pm" src="https://user-images.githubusercontent.com/24502003/43355296-aadc5724-9262-11e8-97e2-13abe20478c3.png">

**Comment by craigloftus** [comment]
I've looked at the service logs for the recruit and close services and there is no indication of an error in them. I can only assume it was a transient issue with the Telerivet data tables.

If it occurs again I'd suggest you ask the Telerivet support staff to look into it?
