### ISSUE TITLE
space between router keyword and the numeric code

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#52]
Currently we must have a space between the router keyword and the numeric code. 

How difficult is it to modify the code to be flexible around it?
- `KAZI123456` as opposed to `KAZI 123456` (i.e. no space)
- `KAZI  123456` as opposed to `KAZI 123456` (i.e. two spaces).

**Comment by craigloftus** [comment]
It will work with two spaces already, and yeah I can drop the requirement for any space at all.

**Comment by craigloftus** [comment]
In fact, I've done it.
