### ISSUE TITLE
Change in "please use the following format: FUNGA 123456"

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#53]
When we say "please use the following format: FUNGA 123456," people do not understand that they need to use their own codes. They just reply the message with the example code 123456 literally.

I know it is difficult for HUDUMA (OFFER) because there can be multiple offers from workers, but for FUNGA (CLOSE), can we use the job code that has been generated?

For example, we could replace that error message by:
`To stop receiving offers, reply: FUNGA [[jobcode]]`

I understand that this would be a problem if an employer makes multiple postings in a given time period, but let me know how hard it would be to add this feature or if you see foresee some problems.

**Comment by craigloftus** [comment]
As you note, it would be hard to make it really robust, but it wouldn't be too hard to do a slightly better job, i.e., use the code of the oldest job they have open, or if they don't have any open, tell them that.

I can do that today in the time remaining.

**Comment by craigloftus** [comment]
@dajeong265 I have created a new inactive close service (for testing purposes), which should address this issue:
https://telerivet.com/p/findjob/service/SVecef6bf5469a8bf5/edit

Please test it and translate the messages and then I will update the original service.

**Comment by dajeong265** [comment]
I see you did some test. I'll also do it on my end and will let you know.

**Comment by dajeong265** [comment]
It looks like it's working well. I have two questions. 

1. How do you switch from the oldest one to a newest job code? Sometimes, employers might not worry about the jobs they posted a month ago because those jobs have already been forgotten by workers, but employers might want to close the job they recently posted because he/she is getting too many applications. Would it be just modifying the command `find_oldest` below to something else:
`var oldest_job = find_oldest();`?

And where does the command come from? Is it a built in command in javascript?


2. How were you planning to migrate this `close 1_swahili (updated)` into the original one, because there's no option to specify the service code we want? Were you just planning to add the logics manually in `close 1_swahili'? If so, I can do that once I am done with the translations, by replicating your logic. I am waiting for my field staff to come back from villages for translations. 

If possible, I just wanted to save your little remaining time on this because I wanted you to work on modifying the numeric code generation in #19.

**Comment by craigloftus** [comment]
I've suggest the most recent open job.

I've updated (and deployed) the custom JS used by the original service, so it is just the case of you updating the conditionals and messages once you have the translations. The updates JS shouldn't effect the functioning of the old service.

**Comment by dajeong265** [comment]
Ok. Thanks. I'll just replicate the `close 1_swahili (updated)` into the original and then will delete this copy.
