### ISSUE TITLE
[Urgent] Quick question about [[$payment]] in Offer 1_swahili

### ISSUE THREAD

**Issue by dajeong265** [regulusweb/ucsc-tz-labor#54]
The global variable, [[$payment]], are not being updated in Offer 1_swahili:

For the following messages:
`Umeshapata ofa ya kazi ya [[$payment]] kwa Shilingi [[$offer]] kutoka kwa kibarua. Kupata maelezo yake jibu: HUDUMA[[$offer_code]]`

`Samahani sijakuelewa. Tafadhalli jibu kwa kutumia namba kwa kiwango cha pesa unachotaraji kulipwa kwa [[$payment]], Mfano: 8000 au 50000`

[[$offer]] and [[$offer_code]] in the same sentence are working fine. But the [[$payment]] are missing. I had thought my recent change has made this not working, but it looks like it has not worked since June 29th (it was working before June 29th).  I am looking into this now, but could you kindly look at it also ASAP if possible?

**Comment by dajeong265** [comment]
Ok. I think I fixed it by saving the global.$payment into a state variable within the Telerivet, state.var.payment. But could you double check my code, <offer 1_swahili>?

I guess the global variable is not valid outside of the current active session?

**Comment by craigloftus** [comment]
Thats correct.
