### ISSUE TITLE
Setup reminders for surveys

### ISSUE THREAD

**Issue by craigloftus** [regulusweb/ucsc-tz-labor#9]
Schedule repeat surveys if the farmer does not respond.

**Comment by craigloftus** [comment]
@dajeong265 Currently the initial prompt for the survey is set to 7 days after the job was initially posted, and then a reminder is sent 2 days after that. These are configurable, but is that a sensible place to start?

**Comment by dajeong265** [comment]
Sounds fine for now.

**Comment by dajeong265** [comment]
To test the survey module, how should I trigger it, because obviously I can't wait for 7 days for it?

**Comment by craigloftus** [comment]
If you looked here: https://telerivet.com/p/2037d5f9/messages?mode=s

That will list any scheduled messages, including those for the surveys, which will give you the survey code to use. After the survey is completed, the survey is closed and the scheduled message will be deleted.

The scheduled message will be created initially the first time you view a workers details, and gets updated for each view after that.

The response data is stored in the `survey_request` data table.

**Comment by dajeong265** [comment]
We’ve been testing it with Survey 1_swahili, but I don’t see anything in the link above. 

Just to reiterate what I said in my email, the Swahili version of the post-hiring survey was added to the Telerivet last Friday there, but I wasn’t sure what you mean by “migrating the swahili services.” Could you elaborate on that just for my education?

**Comment by craigloftus** [comment]
What I meant was that is required changes to the JS across multiple services. In the recruit service to set up an initial survey data entry and in the view service because we want to change the survey for each worker the farmer views.

I'm working on that now.

**Comment by dajeong265** [comment]
Ok. I updated the action. Somehow there's no $ sign in the [[ ]]. I guess that's fine?

**Comment by craigloftus** [comment]
@dajeong265 Is there a reason you've reopened this?

**Comment by dajeong265** [comment]
@craigloftus Just wanted to make sure you saw my comment above: "Somehow there's no $ sign in the [[ ]]." But I see some scheduled messages in the link you gave above https://telerivet.com/p/2037d5f9/messages?mode=s

I presume that means it is working fine? If so you can close it.

**Comment by craigloftus** [comment]
Yeah, that is as intended.

**Comment by dajeong265** [comment]
Craig, I've playing around with the "scheduled messages" for the feedback survey in this link .
https://telerivet.com/p/2037d5f9/messages?mode=s

But they have been programmed to be sent from your UK number. Could you change it to be the main routing number: 255621472172

**Comment by dajeong265** [comment]
Another question is that I want to have farmers to practice these immediately after posting their worker request and after getting at least 1 offer from worker(s). I know how to edit them manually in the scheduled message webpage, but how can I uniformly configure this to be 10-15 minutes later after they post a job announcement as opposed to 7 days?

**Comment by craigloftus** [comment]
I'm not sure why it was using the UK number, it is supposed to use the 'default' route, which should have been yours anyway. I don't need the UK route anymore, so I have removed it, which should address the issue.

Configuring the timing is reasonably simple, it involves editing this line:
https://github.com/regulusweb/ucsc-tz-labor/blob/master/scripts/services/view/action_1.js#L65

I have adjusted it to 10 minutes, but we'll need to remember to set the value back to `604800` after you've tested it.

**Comment by dajeong265** [comment]
I updated it to be 300 (5 minutes), but still it takes 10 minutes for a worker to receive "REVIEW" service. 

Is the above link for FEEDBACK service, REVIEW service, or both?

Incidentally an employer phone is getting the FEEDBACK service instantly after job posting.

**Comment by dajeong265** [comment]
Another thing is that currently we send the reminder twice. We send a second reminder 9 days after the job post if the first one has not been responded.

Do you know what happens if the first one was partially completed?

**Comment by craigloftus** [comment]
> I updated it to be 300 (5 minutes), but still it takes 10 minutes for a worker to receive "REVIEW"
> service. I don't think it's because of the "syncing" with the Telerivet because it's currently synced
> with the most recent git commit.


You'd set the time on one, but not on the one for the review service.

> Incidentally an employer phone is getting the FEEDBACK service instantly after job posting.

If you see issues such as that please make a note of the phonenumber, text and time of the message; without those it is impossible to investigate.

> Do you know what happens if the first one was partially completed?

If it is partially completed they will still be sent the reminder and asked to fill the survey in again. The service **wouldn't** ask for repeat feedback on individual workers.

**Comment by dajeong265** [comment]
Thanks. Just to be clear, the configuration should be done in these files?

Worker: REVIEW reminder 
`scripts/services/offer/action_2.js`

Employer: FEEDBACK reminder
`scripts/services/view/action_1.js`

Also could you tell me where I would configure the "2 days" interval for the 2nd reminder?

**Comment by craigloftus** [comment]
Yes, just those 2 files.

The reminders are specified in `rrule` the lines directly below each place where you're specifying the timing:

```
start_time: parseInt(survey.vars.posted)+300,
rrule: 'FREQ=DAILY;INTERVAL=2;COUNT=2;',
```

```
start_time_offset: 300,
rrule: 'FREQ=DAILY;INTERVAL=2;COUNT=2;',
```

If frequency is daily, then interval is the number of days between each message, and count is the total number of messages to send. So it will send the first one at the start time specified, and then the 2nd one `interval` days later.
